services:
  kafka:
    container_name: "kafka"
    image: "bitnami/kafka:latest"
    env_file:
      - deploy/kafka.env
    volumes:
      - kafka:/bitnami/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    #healthcheck:
    #  test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --topic FIO --describe" ]
    #  interval: 5s
    #  timeout: 5s
    #  retries: 5

  kafka-ui:
    container_name: "kafka-ui"
    image: "provectuslabs/kafka-ui:latest"
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    env_file:
      - deploy/kafka-ui.env

  postgres:
    container_name: "postgres"
    image: "postgres:15-alpine3.18"
    networks:
      db_net:
        aliases:
          - database
    ports:
      - "5432:5432"
    env_file:
      - deploy/postgres.env
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    container_name: "migrate"
    image: "migrate/migrate:latest"
    networks:
      - db_net
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@database:5432/postgres?sslmode=disable", "up"]
    links:
      - postgres

  redis:
    container_name: "redis"
    image: "redis:7.0-alpine3.18"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  peoples-kafka:
    container_name: peoples-kafka
    build:
      context: .
      dockerfile: ./deploy/peoples_kafka/Dockerfile
    environment:
      - CONFIG_PATH=/app/deploy/peoples_kafka/.env
    depends_on:
      - postgres
      - kafka

volumes:
  kafka:
  database:
  cache:
  migrations:

networks:
  db_net: